server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Passa todas as rotas para o React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Headers de segurança
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
}
